filegroup(
    name = "application_config_examples",
    srcs = glob(
        ["application_configs/**/*"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "workflow_request_examples",
    srcs = glob(
        ["workflow_requests/**/*"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "workflow_config_examples",
    srcs = glob(
        ["workflow_configs/**/*"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all_examples",
    srcs = glob(
        [
            "application_configs/**/*",
            "workflow_requests/**/*",
            "workflow_configs/**/*",
        ],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)
