load("//tools/testing:cc_test_defs.bzl", "cc_tests_from_glob")

cc_tests_from_glob(
    size = "small",
    default_deps = [
        "//utils",
        "@googletest//:gtest_main",
    ],
    linkstatic = True,
)
