load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "generator_test",
    size = "small",
    srcs = ["generator_test.cpp"],
    deps = [
        "//utils",
        "@googletest//:gtest_main",
    ],
)
